import type { Theme } from '@skeletonlabs/skeleton/themes';

const supportiveminds = {
  "name": "supportiveminds",
  "properties": {
    "--type-scale-factor": "1.2",
    "--type-scale-1": "calc(0.75rem * var(--type-scale-factor))",
    "--type-scale-2": "calc(0.875rem * var(--type-scale-factor))",
    "--type-scale-3": "calc(1rem * var(--type-scale-factor))",
    "--type-scale-4": "calc(1.125rem * var(--type-scale-factor))",
    "--type-scale-5": "calc(1.25rem * var(--type-scale-factor))",
    "--type-scale-6": "calc(1.5rem * var(--type-scale-factor))",
    "--type-scale-7": "calc(1.875rem * var(--type-scale-factor))",
    "--type-scale-8": "calc(2.25rem * var(--type-scale-factor))",
    "--type-scale-9": "calc(3rem * var(--type-scale-factor))",
    "--type-scale-10": "calc(3.75rem * var(--type-scale-factor))",
    "--type-scale-11": "calc(4.5rem * var(--type-scale-factor))",
    "--type-scale-12": "calc(6rem * var(--type-scale-factor))",
    "--type-scale-13": "calc(8rem * var(--type-scale-factor))",
    "--base-font-color": "var(--color-primary-950)",
    // "--base-font-color-dark": "var(--color-surface-50)",
    "--base-font-family": "Inter, Roboto, Helvetica Neue, Arial Nova, Nimbus Sans, Arial, sans-serif",
    "--base-font-size": "inherit",
    "--base-line-height": "inherit",
    "--base-font-weight": "normal",
    "--base-font-style": "normal",
    "--base-letter-spacing": "0em",
    "--heading-font-color": "var(--color-primary-500)",
    "--heading-font-color-dark": "var(--color-primary-500)",
    "--heading-font-family": "inherit",
    "--heading-font-weight": "bold",
    "--heading-font-style": "normal",
    "--heading-letter-spacing": "inherit",
    "--anchor-font-color": "var(--color-primary-500)",
    "--anchor-font-color-dark": "var(--color-primary-500)",
    "--anchor-font-family": "inherit",
    "--anchor-font-size": "inherit",
    "--anchor-line-height": "inherit",
    "--anchor-font-weight": "inherit",
    "--anchor-font-style": "inherit",
    "--anchor-letter-spacing": "inherit",
    "--anchor-text-decoration": "none",
    "--anchor-text-decoration-hover": "underline",
    "--anchor-text-decoration-active": "none",
    "--anchor-text-decoration-focus": "none",
    "--space-scale-factor": "1.05",
    "--radii-default": "6px",
    "--radii-container": "4px",
    "--border-width-default": "1px",
    "--divide-width-default": "1px",
    "--outline-width-default": "1px",
    "--ring-width-default": "1px",
    "--body-background-color": "var(--color-surface-500)",
    "--body-background-color-dark": "var(--color-surface-500)",
    "--color-primary-50": "142 158 149",
    "--color-primary-100": "121 136 127",
    "--color-primary-200": "99 114 106",
    "--color-primary-300": "78 92 84",
    "--color-primary-400": "56 70 63",
    "--color-primary-500": "35 48 41",
    "--color-primary-600": "29 39 33",
    "--color-primary-700": "22 30 26",
    "--color-primary-800": "16 21 18",
    "--color-primary-900": "9 12 11",
    "--color-primary-950": "3 3 3",
    "--color-primary-contrast-dark": "var(--color-primary-950)",
    "--color-primary-contrast-light": "var(--color-primary-50)",
    "--color-primary-contrast-50": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-100": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-200": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-300": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-400": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-500": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-600": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-700": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-800": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-900": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-950": "var(--color-primary-contrast-light)",
    "--color-secondary-50": "255 255 206",
    "--color-secondary-100": "242 234 182",
    "--color-secondary-200": "230 212 158",
    "--color-secondary-300": "217 191 135",
    "--color-secondary-400": "205 169 111",
    "--color-secondary-500": "192 148 87",
    "--color-secondary-600": "168 126 70",
    "--color-secondary-700": "143 105 52",
    "--color-secondary-800": "119 83 35",
    "--color-secondary-900": "94 62 17",
    "--color-secondary-950": "70 40 0",
    "--color-secondary-contrast-dark": "var(--color-secondary-950)",
    "--color-secondary-contrast-light": "var(--color-secondary-50)",
    "--color-secondary-contrast-50": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-100": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-200": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-300": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-400": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-500": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-600": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-700": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-800": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-900": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-950": "var(--color-secondary-contrast-light)",
    "--color-tertiary-50": "235 255 255",
    "--color-tertiary-100": "210 236 231",
    "--color-tertiary-200": "186 218 207",
    "--color-tertiary-300": "161 199 184",
    "--color-tertiary-400": "137 181 160",
    "--color-tertiary-500": "112 162 136",
    "--color-tertiary-600": "90 140 115",
    "--color-tertiary-700": "67 118 94",
    "--color-tertiary-800": "45 95 73",
    "--color-tertiary-900": "22 73 52",
    "--color-tertiary-950": "0 51 31",
    "--color-tertiary-contrast-dark": "var(--color-tertiary-950)",
    "--color-tertiary-contrast-light": "var(--color-tertiary-50)",
    "--color-tertiary-contrast-50": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-100": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-200": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-300": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-400": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-500": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-600": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-700": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-800": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-900": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-950": "var(--color-tertiary-contrast-light)",
    "--color-success-50": "255 255 255",
    "--color-success-100": "242 252 231",
    "--color-success-200": "228 249 206",
    "--color-success-300": "215 247 182",
    "--color-success-400": "201 244 157",
    "--color-success-500": "188 241 133",
    "--color-success-600": "164 216 109",
    "--color-success-700": "139 192 85",
    "--color-success-800": "115 167 60",
    "--color-success-900": "90 143 36",
    "--color-success-950": "66 118 12",
    "--color-success-contrast-dark": "var(--color-success-950)",
    "--color-success-contrast-light": "var(--color-success-50)",
    "--color-success-contrast-50": "var(--color-success-contrast-dark)",
    "--color-success-contrast-100": "var(--color-success-contrast-dark)",
    "--color-success-contrast-200": "var(--color-success-contrast-dark)",
    "--color-success-contrast-300": "var(--color-success-contrast-dark)",
    "--color-success-contrast-400": "var(--color-success-contrast-dark)",
    "--color-success-contrast-500": "var(--color-success-contrast-dark)",
    "--color-success-contrast-600": "var(--color-success-contrast-dark)",
    "--color-success-contrast-700": "var(--color-success-contrast-dark)",
    "--color-success-contrast-800": "var(--color-success-contrast-light)",
    "--color-success-contrast-900": "var(--color-success-contrast-light)",
    "--color-success-contrast-950": "var(--color-success-contrast-light)",
    "--color-warning-50": "255 255 253",
    "--color-warning-100": "252 248 228",
    "--color-warning-200": "249 241 203",
    "--color-warning-300": "246 235 177",
    "--color-warning-400": "243 228 152",
    "--color-warning-500": "240 221 127",
    "--color-warning-600": "215 197 103",
    "--color-warning-700": "189 173 78",
    "--color-warning-800": "164 150 54",
    "--color-warning-900": "138 126 29",
    "--color-warning-950": "113 102 5",
    "--color-warning-contrast-dark": "var(--color-warning-950)",
    "--color-warning-contrast-light": "var(--color-warning-50)",
    "--color-warning-contrast-50": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-100": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-200": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-300": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-400": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-500": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-600": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-700": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-800": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-900": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-950": "var(--color-warning-contrast-light)",
    "--color-error-50": "255 243 255",
    "--color-error-100": "247 218 234",
    "--color-error-200": "238 193 214",
    "--color-error-300": "230 168 193",
    "--color-error-400": "221 143 173",
    "--color-error-500": "213 118 152",
    "--color-error-600": "188 94 130",
    "--color-error-700": "163 71 109",
    "--color-error-800": "138 47 87",
    "--color-error-900": "113 24 66",
    "--color-error-950": "88 0 44",
    "--color-error-contrast-dark": "var(--color-error-950)",
    "--color-error-contrast-light": "var(--color-error-50)",
    "--color-error-contrast-50": "var(--color-error-contrast-dark)",
    "--color-error-contrast-100": "var(--color-error-contrast-dark)",
    "--color-error-contrast-200": "var(--color-error-contrast-dark)",
    "--color-error-contrast-300": "var(--color-error-contrast-dark)",
    "--color-error-contrast-400": "var(--color-error-contrast-dark)",
    "--color-error-contrast-500": "var(--color-error-contrast-dark)",
    "--color-error-contrast-600": "var(--color-error-contrast-light)",
    "--color-error-contrast-700": "var(--color-error-contrast-light)",
    "--color-error-contrast-800": "var(--color-error-contrast-light)",
    "--color-error-contrast-900": "var(--color-error-contrast-light)",
    "--color-error-contrast-950": "var(--color-error-contrast-light)",
    "--color-surface-50": "255 255 255",
    "--color-surface-100": "254 253 252",
    "--color-surface-200": "253 251 249",
    "--color-surface-300": "251 250 246",
    "--color-surface-400": "250 248 243",
    "--color-surface-500": "249 246 240",
    "--color-surface-600": "224 222 216",
    "--color-surface-700": "200 197 191",
    "--color-surface-800": "175 173 167",
    "--color-surface-900": "151 148 142",
    "--color-surface-950": "126 124 118",
    "--color-surface-contrast-dark": "var(--color-surface-950)",
    "--color-surface-contrast-light": "var(--color-surface-50)",
    "--color-surface-contrast-50": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-100": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-200": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-300": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-400": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-500": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-600": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-700": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-800": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-900": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-950": "var(--color-surface-contrast-light)"
  },
  "metadata": {
    "version": "3.0.0"
  }
} satisfies Theme;

export default supportiveminds;